export const cuisineCategories = [
  'Bangladeshi',
  'Bengali',
  'Indian',
  'Pakistani',
  'Nepali',
  'Sri Lankan',
  'Chinese',
  'Japanese',
  'Korean',
  'Thai',
  'Vietnamese',
  'Indonesian',
  'Malaysian',
  'Turkish',
  'Arabian',
  'Persian',
  'Italian',
  'French',
  'Spanish',
  'Mexican',
  'American',
  'Greek',
  'Mediterranean',
  'British',
  'African',
  'International'
] as const